apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: 218146516368.dkr.ecr.us-east-1.amazonaws.com/web_ecr:v0.1
        name: myapp
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: DBPORT
          value: "3306"
        - name: DBHOST
          value: "10.100.147.109"
        - name: DBUSER
          value: root
        - name: DBPWD
          value: pw
      volumes:
      - name: myapp-data
        hostPath:
          path: /var/www/html
