apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  volumes:
  - name: mysql-data
    awsElasticBlockStore:
      volumeID: vol-02f90e420c5ed2c92
      fsType: ext4
  containers:
  - image: mongo
    name: mongodb
    volumeMounts:
    - name: mysql-data
      mountPath: /data/db
    ports:
    - containerPort: 27017
      protocol: TCP
