apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      application: mysql
  template:
    metadata:
      labels:
        application: mysql
    spec:
      containers:
      - name: mysql
        image: 218146516368.dkr.ecr.us-east-1.amazonaws.com/mysql_ecr:v1.0
        ports:
        - containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: pw
        volumeMounts:
        - mountPath: /data/db
          name: mysql-data
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
