apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      application: mysql
  template:
    metadata:
      labels:
        application: mysql
        version: 3.2.5
    spec:
      containers:
      - name: mysql
        image: redis:3.2.5
        volumeMounts:
        - mountPath: /data
          name: mysql-data
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data